# Some overrides can not be automatically generated by update-overrides.sh
{ lib, fetchFromGitHub, ... }:
self: super: {
    # django-maintenance-mode patch is broken on latest nixos-unstable?
    django-maintenance-mode = super.django-maintenance-mode.overrideAttrs (old: {
        patches = [];
    });
}