# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "django-dbbackup" = super.buildPythonPackage rec {
    pname = "django-dbbackup";
    version = "4.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/24/1d635364f42dad1d5213a97ada58eccbff8c0a1da906111aca90c0e0c370/django_dbbackup-4.0.2-py3-none-any.whl";
      sha256 = "0apa15611mwwhlgay8rhc9bbbaz35mz8wymk66q8y9m8y4qyik9w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pytz"
    ];
  };
  "django-error-report-2" = super.buildPythonPackage rec {
    pname = "django-error-report-2";
    version = "0.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/df/b0985db6c0e3feadf054b3f2c9df281d8eb7463a32a903a549ae21233eb7/django_error_report_2-0.4.2-py3-none-any.whl";
      sha256 = "06vc5z37n60fl1p7k42kkl51af0qa08gkfjzkylpx6zhg94rrn8x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-flags" = super.buildPythonPackage rec {
    pname = "django-flags";
    version = "5.0.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/05/7715921dc6599eb2f40f68b85975ae6567e4325b949e29701eb380d9d37f/django_flags-5.0.13-py2.py3-none-any.whl";
      sha256 = "0hkaq2iqnbkg3agih5p0x4kz382viav2dbch450cpxckdnw79psj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-ical" = super.buildPythonPackage rec {
    pname = "django-ical";
    version = "1.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/3f/647857462fa4169cb855aaf14969a6843f3910a3781d7c17f18c460b0e08/django_ical-1.9.2-py3-none-any.whl";
      sha256 = "0w6y24n94jjlvk7sd67nm69a4fiw1wjxgji006h92pvk0p56p8bl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-recurrence"
      self."icalendar"
    ];
  };
  "django-markdownify" = super.buildPythonPackage rec {
    pname = "django-markdownify";
    version = "0.9.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/b5/d02b5b26aea38a3b3d1cc1fec9420be5b26d53e14ba0e1d06117285fad15/django_markdownify-0.9.3-py3-none-any.whl";
      sha256 = "1rnyxb82fv9k8d7c1dv6s8ihdhqjzi8jfh4rz6g0nh1qqcdjj06z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bleach"
      self."django"
      self."markdown"
    ];
  };
  "django-money" = super.buildPythonPackage rec {
    pname = "django-money";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/b1/9e8d1d48378d17f03cd2a9b11f705e05bc3a4b90c5b43e82b8cf91538098/django_money-3.2.0-py3-none-any.whl";
      sha256 = "0nalc9z5k63vyx10vx80zwjwabqf4mfgzwvfnl3ayxbi803gk69h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."py-moneyed"
      self."setuptools"
    ];
  };
  "django-q-sentry" = super.buildPythonPackage rec {
    pname = "django-q-sentry";
    version = "0.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/2e/7efdeff904400fba89428438c21ef3617c31544b17adbc17f4856b42369d/django_q_sentry-0.1.6-py3-none-any.whl";
      sha256 = "0l6hz1p1gr5ivd4qhp7lgs5hg0zakl6sphpj8yd7sfi5mmzlv2wv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sentry-sdk"
    ];
  };
  "django-q2" = super.buildPythonPackage rec {
    pname = "django-q2";
    version = "1.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/10/0080332276ea7cf3289a277e3655096799e721002c2eae6083ae170d266d/django_q2-1.6.1-py3-none-any.whl";
      sha256 = "0zbzm9nzxw5zyp7qcjbn4ji51mwlw83kh2lpz9qx8w9nnz5vci09";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."django-picklefield"
      self."importlib-metadata"
    ];
  };
  "django-recurrence" = super.buildPythonPackage rec {
    pname = "django-recurrence";
    version = "1.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/0a/5dc0f1f408a5b5f00c64ec57f3868248ed65ee660980118867b1279eca96/django_recurrence-1.11.1-py3-none-any.whl";
      sha256 = "1iaby5csbbakly848rr89y4mag52mlnrbdmsm49mi6srf84g6r8c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."python-dateutil"
    ];
  };
  "django-sql-utils" = super.buildPythonPackage rec {
    pname = "django-sql-utils";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/59/a5354087ece4b22465f9a31458ec182d1d54305994ecd6cc8bd8eedd7e43/django_sql_utils-0.7.0-py3-none-any.whl";
      sha256 = "0cm5jpbscfyd71j005jsjmccjgsj1givcd9yygy60sw94v441z7y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."sqlparse"
    ];
  };
  "django-sslserver" = super.buildPythonPackage rec {
    pname = "django-sslserver";
    version = "0.22";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/97/e4011f3944f83a7d2aaaf893c3689ad70e8d2ae46fb6e14fd0e3b0c6ce0b/django_sslserver-0.22-py3-none-any.whl";
      sha256 = "1ia754fg55i8997bg9d38y70xy3k165kvnwdq0hj9p6cs9is7665";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-stdimage" = super.buildPythonPackage rec {
    pname = "django-stdimage";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/e4/f90e895cb97bd625c9d162dc7919addd6321d34023439623abb6e4c99f30/django_stdimage-6.0.2-py2.py3-none-any.whl";
      sha256 = "1j11spri5qd7i3xw97abprfr6r3ivddjs0rb1rc7906493dgfwws";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."pillow"
    ];
  };
  "django-user-sessions" = super.buildPythonPackage rec {
    pname = "django-user-sessions";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/f4/fab7937669540636bacd421cf30adbbfa8dc41a2f84f175e8fc133907776/django_user_sessions-2.0.0-py3-none-any.whl";
      sha256 = "0j3pqsf5ksmjhjz1s041qnxlbbmk13x0jmlnc9qb8mpmg515ar89";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "django-weasyprint" = super.buildPythonPackage rec {
    pname = "django-weasyprint";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/a2/380a826e57eb97f30d21f46cc6074af5ef0b2f5cfcc4343540771a26fde9/django_weasyprint-2.2.1-py3-none-any.whl";
      sha256 = "02q9363a36qqaylxs69pl6kkmljx8nkq1ksmlc4iv3xkgs4qrr4c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
      self."weasyprint"
    ];
  };
  "django-xforwardedfor-middleware" = super.buildPythonPackage rec {
    pname = "django-xforwardedfor-middleware";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/79/a770c32c1927720cf44e48ac6adb70986253e83d3948c1e5fd152e432db7/django-xforwardedfor-middleware-2.0.tar.gz";
      sha256 = "090b1x25rv0lksv5a4ksy9v4lcxpn6pl62rydwdm999kgyr1rz8n";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."django"
    ];
  };
  "py-moneyed" = super.buildPythonPackage rec {
    pname = "py-moneyed";
    version = "3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/2b/2d87f12edc70f0d8c85148c51b57a4b8cf89e4d8ad291935a47ed1b7c52e/py_moneyed-3.0-py3-none-any.whl";
      sha256 = "1fyrfqv76zpwkkp5x2pw7623rdz90r91in4kc4clcny0k57s30wm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."babel"
      self."typing-extensions"
    ];
  };
}
